name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Verify
      run: |
        pwd
        ls -ltr
        ls -ltr target/
        cd target/
        ls -ltr
        cd debug/
        ls -ltr
